#!/bin/bash
cd /var/www/lulusistemas.com.br
echo Removing current website folder...
sudo rm -r public_html
echo Copying project files...
sudo cp -r /menezes/projetos/lulusistemas/web public_html
echo Copying javascript library files...
sudo cp -r /menezes/codigo/javascript3/* public_html/js/